language: c++
sudo: required

addons:
  apt:
    update: true
    sources:      
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - libmetis-dev
      - libblas-dev
      - liblapack-dev
      - libhwloc-dev

before_script:
  - chmod +x ./ci/makebuild.sh
  - export CC=gcc-8
  - export CXX=g++-8
  - export FC=gfortran-8
  - mkdir $TRAVIS_BUILD_DIR/builds && mkdir $TRAVIS_BUILD_DIR/builds/starpu-1.3.3 
  - wget starpu.gforge.inria.fr/files/starpu-1.3.3/starpu-1.3.3.tar.gz
  - tar -xzvf starpu-1.3.3.tar.gz
  - mkdir starpu-1.3.3/build
  - cd starpu-1.3.3/build && ../configure --prefix=$TRAVIS_BUILD_DIR/builds/starpu-1.3.3 && make && make install 

script:
  - ./ci/makebuild.sh
