language: c++
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-8
      - gcc-8
      - g++-8
      - libmetis-dev
      - libblas-dev
      - liblapack-dev
      - libhwloc-dev
      - libstarpu-1.3
      - libstarpu-dev

before_script:
  - chmod +x makebuild.sh
  - export CC=gcc-8
  - export CXX=g++-8
  - export FC=gfortran-8

script:
  - ./ci/makebuild.sh
