language: c++
sudo: required

addons:
  apt:
    update: true
    sources:      
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - gfortran-8
      - libmetis-dev
      - libblas-dev
      - liblapack-dev
      - libhwloc-dev

before_script:
  - chmod +x ./ci/makebuild.sh
  - export CC=gcc-8
  - export CXX=g++-8
  - export FC=gfortran-8
  - mkdir $TRAVIS_BUILD_DIR/builds
  - mkdir $TRAVIS_BUILD_DIR/builds/starpu-1.3.3 
  - wget starpu.gforge.inria.fr/files/starpu-1.3.3/starpu-1.3.3.tar.gz
  - tar -xzvf starpu-1.3.3.tar.gz
  - mkdir starpu-1.3.3/build
  - cd starpu-1.3.3/build && ../configure --prefix=$TRAVIS_BUILD_DIR/builds/starpu-1.3.3 --disable-build-doc --disable-build-examples --disable-opencl --disable-starpufft --disable-mpi --disable-openmp --disable-fxt --enable-blas-lib=none && make && make install
  - export STARPU_DIR=$TRAVIS_BUILD_DIR/builds/starpu-1.3.3
  - export LD_LIBRARY_PATH=$STARPU_DIR/lib:$LD_LIBRARY_PATH
  - cd -

script:
  - pwd && ls
  - echo $CC && echo $CXX && echo $FC
  - echo $STARPU_DIR && echo $STARPU_DIR/lib 
  - echo $LD_LIBRARY_PATH
  - mkdir builds/sylver-starpu
  - cd builds/sylver-starpu
  - which cmake
  - cmake ../.. -D SYLVER_RUNTIME=StarPU -D SYLVER_ENABLE_CUDA=OFF -D SYLVER_ENABLE_OMP=OFF -D SYLVER_SPRAL_USE_INTERNAL=ON -D SYLVER_BUILD_UNIT_TESTS=ON
